In [1]:
import pandas as pd

PATH = "./data/"

In [2]:
df_raw = pd.read_csv(PATH+"crashes.csv")
df_raw.head()

,-,Date,Time,Location,Operator,Flight #,Route,AC Type,Registration,cn / ln,Aboard,Fatalities,Ground,Summary
0,ACCIDENT DETAILS,"September 17, 1908",1718,"Fort Myer, Virginia",Military - U.S. Army,?,Demonstration,Wright Flyer III,?,1,2 (passengers:1 crew:1),1 (passengers:1 crew:0),0,"During a demonstration flight, a U.S. Army fly..."
1,ACCIDENT DETAILS,"September 07, 1909",?,"Juvisy-sur-Orge, France",?,?,Air show,Wright Byplane,SC1,?,1 (passengers:0 crew:1),1 (passengers:0 crew:0),0,Eugene Lefebvre was the first pilot to ever be...
2,ACCIDENT DETAILS,"July 12, 1912",0630,"Atlantic City, New Jersey",Military - U.S. Navy,?,Test flight,Dirigible,?,?,5 (passengers:0 crew:5),5 (passengers:0 crew:5),0,First U.S. dirigible Akron exploded just offsh...
3,ACCIDENT DETAILS,"August 06, 1913",?,"Victoria, British Columbia, Canada",Private,?,?,Curtiss seaplane,?,?,1 (passengers:0 crew:1),1 (passengers:0 crew:1),0,The first fatal airplane accident in Canada oc...
4,ACCIDENT DETAILS,"September 09, 1913",1830,Over the North Sea,Military - German Navy,?,?,Zeppelin L-1 (airship),?,?,20 (passengers:? crew:?),14 (passengers:? crew:?),0,The airship flew into a thunderstorm and encou...

In [3]:
df = df_raw[["Date", "Time", "Location", "Operator", "Flight #", "Route", "AC Type", "Aboard", "Fatalities", "Ground"]]
df["Date"] = pd.to_datetime(df["Date"], format="%B %d, %Y")
df["Year"] = df["Date"].dt.year
df["Operator"] = df["Operator"].str.split(" /").str[0].str.split(" -").str[0].str.lower().astype(str)
df["Operator"] = df["Operator"].str.replace("air lines", "airlines")
df["Aboard"] = pd.to_numeric(df["Aboard"].str.split().str[0], errors="coerce")
df["Fatalities"] = pd.to_numeric(df["Fatalities"].str.split().str[0], errors="coerce")
df["AC mfr"] = df["AC Type"].str.split().str[0].str.lower().astype(str)
df["Departure"] = df["Route"].str.split(" -").str[0].where(df["Route"].str.contains("-"), "?").astype(str)
df["Arrival"] = df["Route"].str[::-1].str.split(" -").str[0].str[::-1].where(df["Route"].str.contains("-"), "?").astype(str)
df.head()

,Date,Time,Location,Operator,Flight #,Route,AC Type,Aboard,Fatalities,Ground,Year,AC mfr,Departure,Arrival
0,1908-09-17,1718,"Fort Myer, Virginia",military,?,Demonstration,Wright Flyer III,2.0,1.0,0,1908,wright,?,?
1,1909-09-07,?,"Juvisy-sur-Orge, France",?,?,Air show,Wright Byplane,1.0,1.0,0,1909,wright,?,?
2,1912-07-12,0630,"Atlantic City, New Jersey",military,?,Test flight,Dirigible,5.0,5.0,0,1912,dirigible,?,?
3,1913-08-06,?,"Victoria, British Columbia, Canada",private,?,?,Curtiss seaplane,1.0,1.0,0,1913,curtiss,?,?
4,1913-09-09,1830,Over the North Sea,military,?,?,Zeppelin L-1 (airship),20.0,14.0,0,1913,zeppelin,?,?

In [4]:
df.dtypes

Date          datetime64[us]
Time                     str
Location                 str
Operator                 str
Flight #                 str
Route                    str
AC Type                  str
Aboard               float64
Fatalities           float64
Ground                   str
Year                   int32
AC mfr                   str
Departure                str
Arrival                  str
dtype: object

In [5]:
df.to_csv(PATH+"crashes_cleaned.csv")

In [6]:
df_airlines = pd.read_csv(PATH+"airlines.dat",
    names = ["Airline ID", "Name", "Alias", "IATA", "ICAO", "Callsign", "Country", "Active"])
df_airlines.head()

,Airline ID,Name,Alias,IATA,ICAO,Callsign,Country,Active
0,-1,Unknown,\N,-,NaN,\N,\N,Y
1,1,Private flight,\N,-,NaN,NaN,NaN,Y
2,2,135 Airways,\N,NaN,GNL,GENERAL,United States,N
3,3,1Time Airline,\N,1T,RNX,NEXTIME,South Africa,Y
4,4,2 Sqn No 1 Elementary Flying Training School,\N,NaN,WYT,NaN,United Kingdom,N

In [7]:
df_airports = pd.read_csv(PATH+"airports.dat",
    names = ["Airport ID", "Name", "City", "Country", "IATA", "ICAO", "Latitude", "Longitude", "Altitude", "Timezone", "DST", "Tz timezone", "Type", "Source"])
df_airports.head()

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz timezone,Type,Source
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10,U,Pacific/Port_Moresby,airport,OurAirports
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10,U,Pacific/Port_Moresby,airport,OurAirports
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10,U,Pacific/Port_Moresby,airport,OurAirports
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10,U,Pacific/Port_Moresby,airport,OurAirports
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10,U,Pacific/Port_Moresby,airport,OurAirports

In [8]:
df_routes = pd.read_csv(PATH+"routes.dat",
    names = ["Airline", "Airline ID", "Source Airport", "Source Airport ID", "Destination Airport", "Destination Airport ID", "Codeshare", "Stops", "Equipment"])
df_routes.head()

,Airline,Airline ID,Source Airport,Source Airport ID,Destination Airport,Destination Airport ID,Codeshare,Stops,Equipment
0,2B,410,AER,2965,KZN,2990,NaN,0,CR2
1,2B,410,ASF,2966,KZN,2990,NaN,0,CR2
2,2B,410,ASF,2966,MRV,2962,NaN,0,CR2
3,2B,410,CEK,2968,KZN,2990,NaN,0,CR2
4,2B,410,CEK,2968,OVB,4078,NaN,0,CR2